# Generated by Django 4.2.5 on 2023-11-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brandName", models.CharField(max_length=200)),
                ("displayName", models.CharField(max_length=500)),
                ("heroImage", models.ImageField(upload_to="")),
                ("moreColors", models.IntegerField()),
                ("displayPrice", models.DecimalField(decimal_places=2, max_digits=7)),
                ("displayRating", models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
