# Generated by Django 4.2.5 on 2024-01-01 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_orderitem_product_delete_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
    ]
